### ISSUE TITLE
Histogram:add looks suspicious

### ISSUE THREAD

**Issue by ccollie** [inspiredware/node-hdr-histogram-napi#1]
It seems that it's adding to itself

https://github.com/inspiredware/node-hdr-histogram-napi/blob/master/binding-src/binding/hdr_histogram.cc#L125

**Comment by jschlight** [comment]
Excellent catch. I will look at this.

**Comment by jschlight** [comment]
I added a unit test to verify the `add` was failing as reported, updated the generator to generate correct code in this case, and verified the unit test is now running correctly.

**Comment by ccollie** [comment]
Thanks for this. This was one of the only issues preventing me from using a native extension.
